version: '3.6'
services:

  tiny-app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - tiny-database
    depends_on:
      - tiny-database
    env_file:
      - ./var/.env

  tiny-database:
    image: 'postgres'
    container_name: 'tiny-database'
    env_file:
      - ./.env
    volumes:
      - ./var/tiny-database-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  tiny-pgadmin:
    image: dpage/pgadmin4
    container_name: 'tiny-database-admin'
    env_file:
      - ./.env
    links:
      - tiny-database
    depends_on:
      - tiny-database
    volumes:
      - ./var/tiny-pgadmin:/root/.pgadmin
    ports:
      - '5050:80'

  tiny-minio:
    container_name: minio
    command: server --console-address :9001 --address :9000 /data
    env_file:
      - ./var/.env
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'

    volumes:
      - ./var/minio:/data
      - ./var/minio/conf/:/root/.minio
    restart: unless-stopped
